
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='panel-bootstrap-vue',
    version='0.1.2',
    description='Use bootstrap-vue VueJs components supporting Bootstrap 4 in Panel templates.',
    python_requires='==3.*,>=3.6.0',
    author='Paulo Lopes',
    author_email='paulopes00@gmail.com',
    license='Apache-2.0',
    packages=['panel_bootstrap_vue'],
    package_dir={"": "."},
    package_data={"panel_bootstrap_vue": ["www/bootstrap/*.css", "www/typography/*.css", "www/typography/fonts/adobe-source-sans-pro/*.woff", "www/typography/fonts/font-awesome/*.woff", "www/vue/*.css", "www/vue/*.js"]},
    install_requires=['panel==0.*,>=0.9.7', 'panel-components==0.*,>=0.1.0'],
)
